### ISSUE TITLE
Cannot click to enable/disable.

### ISSUE THREAD

**Issue by kathampy** [muzuiget/user_agent_overrider#20]
Please re-add the ability to click on the icon to quickly toggle the extension on / off.

**Comment by Gitoffthelawn** [comment]
+1

I was disappointed to see this functionality removed.  It was faster and easier to use before the change.

**Comment by muzuiget** [comment]
Oh, some users suggested me to remove this feature, even an AMO reviewer, I was rejected to full review because

> If the user clicks the button when the UserAgent is not selected, the menu panel is closed - should be displayed menu or as I suggest a panelview. Now for display menu with UserAgents user have to click triangle. So please correct this issue or inform users on add-on page that for choose UserAgent user have to click triangle next to the icon.

And exist two methods to enable/disable make user confuse, and also a bit pain to maintain the code.

So, won't fix.

**Comment by Gitoffthelawn** [comment]
See this popular extension: https://addons.mozilla.org/firefox/addon/nimbus-screenshot/
for a way to use the drop-down arrow for a menu, but still have functionality assigned to the main button.

**Comment by muzuiget** [comment]
It is not technology problem, it is design.

**Comment by Gitoffthelawn** [comment]
If I'm understanding that AMO reviewer correctly (their verbiage is not clear), they don't want a toggle button to act like a toggle button; they want it to act like the drop-down button.  That is contrary to the design of every Firefox extension I've ever tested or designed.  I think they are leading you down the wrong path.

Extensions that have a drop-down button typically use the main button as a toggle, and use the drop-down button to show the drop-down menu.  Otherwise, there is no purpose to the drop-down button.
